In [5]:
#Python code to demonstrate sorting in JSON. 
import json 
data='''{   
   "Student":[   
      {   
         "enrollment_no":"9915103000", 
         "name":"Monika", 
         "subject":[   
            {   
               "code":"DBMS", 
               "grade":"C" 
            } 
         ] 
      }, 
      {   
         "enrollment_no":"8815103057", 
         "name":"Ram", 
         "subject":[   
            {   
               "code":"Python", 
               "grade":"A" 
            }, 
            {   
               "code":"C++", 
               "grade":"A+" 
            } 
         ] 
      } 
   ] 
}'''  


json_parse = json.loads(data)   
for it in json_parse['Student']: 
    for y in it['subject']: 
        print(y['code'],y['grade'],it['enrollment_no'],it['name']) 

DBMS C 9915103000 Monika
Python A 8815103057 Ram
C++ A+ 8815103057 Ram


In [8]:
tuple = (1, 2, 'hi')
print(len(tuple))  ## 3
print(tuple[2])    ## hi
tuple = (1, 2, 'bye')  
 


3
hi


In [9]:
#NUMPY= NUMERICAL PYTHON

In [21]:
import numpy
import numpy as np
cvalues = [20.1, 20.8, 21.9, 22.5, 22.7, 22.3, 21.8, 21.2, 20.9, 20.1]

C = np.array(cvalues)
print(C)
print(type(C))

print(C * 9 / 5 + 32)


[20.1 20.8 21.9 22.5 22.7 22.3 21.8 21.2 20.9 20.1]
<class 'numpy.ndarray'>
[68.18 69.44 71.42 72.5  72.86 72.14 71.24 70.16 69.62 68.18]


In [11]:
import numpy as np
 
a = np.arange(1, 10)
print(a)

x = range(1, 10)
print(x)    # x is an iterator
print(list(x))

x = np.arange(10.4)
print(x)

x = np.arange(0.5, 10.4, 0.8)
print(x)

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [26]:

import numpy as np
 
# 50 values between 1 and 10:
print(np.linspace(1,10,7))
print(np.linspace(1, 10, 5, endpoint=False,retstep=True))
print(np.linspace(1,4,2,retstep=True))
print(np.linspace(1,4,3))
 
 

[ 1.   2.5  4.   5.5  7.   8.5 10. ]
(array([1. , 2.8, 4.6, 6.4, 8.2]), 1.8)
(array([1., 4.]), 3.0)
[1.  2.5 4. ]


#GET COUNT BY STATUS USING PANDAS DATAFRAME

In [2]:
import numpy as np
import pandas as pd
NaN = np.nan
dataframe = pd.DataFrame({'Name': ['Shobhit', 'Vaibhav',
                                   'Vimal', 'Sourabh',
                                   'Rahul', 'Shobhit'],
                          'Physics': [11, 12, 13, 14, NaN, 11],
                          'Chemistry': [10, 14, NaN, 18, 20, 10],
                          'Math': [13, 10, 15, NaN, NaN, 13]})
print(dataframe.count())
print(dataframe.isnull().sum())
 
# it will give the total null
# values present in our dataframe
print("Total Null values count: ",
      dataframe.isnull().sum().sum())
 
 
 
 

Name         6
Physics      5
Chemistry    5
Math         4
dtype: int64
Name         0
Physics      1
Chemistry    1
Math         2
dtype: int64
Total Null values count:  4


In [4]:

# importing Libraries
import pandas as pd
import numpy as np
 
# Creating dataframe using dictionary
NaN = np.nan
dataframe = pd.DataFrame({'Name': ['Shobhit', 'Vaibhav',
                                  'Vimal', 'Sourabh',
                                  'Rahul', 'Shobhit'],
                         'Physics': [11, 12, 13, 14, NaN, 11],
                         'Chemistry': [10, 14, NaN, 18, 20, 10],
                         'Math': [13, 10, 15, NaN, NaN, 13]})
 
print("Created Dataframe")
print(dataframe)
 
# finding Count of all columns
print("Count of all values wrt columns")
print(dataframe.count())
 
# Count according to rows
print("Count of all values wrt rows")
print(dataframe.count(axis=1))
print(dataframe.count(axis='columns'))
 
# count of null values
print("Null Values counts ")
print(dataframe.isnull().sum())
print("Total null values",
     dataframe.isnull().sum().sum())
 
# count of student with greater
# than 11 marks in physics
print("Count of students with physics marks greater than 11 is->",
     dataframe[dataframe['Physics'] > 11]['Name'].count())
 
# resultant of above dataframe
print(dataframe[dataframe['Physics'] > 11])
print("Count of students ->",
     dataframe[(dataframe['Physics'] > 10) &
               (dataframe['Chemistry'] > 11) &
               (dataframe['Math'] > 9)]['Name'].count())
 
print(dataframe[(dataframe['Physics'] > 10) &
               (dataframe['Chemistry'] > 11) &
               (dataframe['Math'] > 9)])

Created Dataframe
      Name  Physics  Chemistry  Math
0  Shobhit     11.0       10.0  13.0
1  Vaibhav     12.0       14.0  10.0
2    Vimal     13.0        NaN  15.0
3  Sourabh     14.0       18.0   NaN
4    Rahul      NaN       20.0   NaN
5  Shobhit     11.0       10.0  13.0
Count of all values wrt columns
Name         6
Physics      5
Chemistry    5
Math         4
dtype: int64
Count of all values wrt rows
0    4
1    4
2    3
3    3
4    2
5    4
dtype: int64
0    4
1    4
2    3
3    3
4    2
5    4
dtype: int64
Null Values counts 
Name         0
Physics      1
Chemistry    1
Math         2
dtype: int64
Total null values 4
Count of students with physics marks greater than 11 is-> 3
      Name  Physics  Chemistry  Math
1  Vaibhav     12.0       14.0  10.0
2    Vimal     13.0        NaN  15.0
3  Sourabh     14.0       18.0   NaN
Count of students -> 1
      Name  Physics  Chemistry  Math
1  Vaibhav     12.0       14.0  10.0


# read a csv file using pandas

In [9]:
import pandas as pd
df = pd.read_csv("diabetes.csv",delimiter=",")
print(df.head)
 


<bound method NDFrame.head of      Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50 

#TYPES OF JOINS IN PANDAS

In [10]:
import pandas as pd
a = pd.DataFrame()
d = {'id': [1, 2, 10, 12], 
     'val1': ['a', 'b', 'c', 'd']} 
a = pd.DataFrame(d)
a

id val1
0   1    a
1   2    b
2  10    c
3  12    d

In [11]:
import pandas as pd
 b = pd.DataFrame()
d = {'id': [1, 2, 9, 8],
     'val1': ['p', 'q', 'r', 's']}
b = pd.DataFrame(d)
b

id val1
0   1    p
1   2    q
2   9    r
3   8    s

In [12]:
#INNER JOIN 

In [13]:
import pandas as pd
a = pd.DataFrame()
d = {'id': [1, 2, 10, 12],
     'val1': ['a', 'b', 'c', 'd']}
 
a = pd.DataFrame(d)
b = pd.DataFrame()
 
d = {'id': [1, 2, 9, 8],
     'val1': ['p', 'q', 'r', 's']}
b = pd.DataFrame(d)
 
# inner join
df = pd.merge(a, b, on='id', how='inner')
df

id val1_x val1_y
0   1      a      p
1   2      b      q

In [14]:
#LEFT JOIN

In [15]:
import pandas as pd

a = pd.DataFrame()
d = {'id': [1, 2, 10, 12],
     'val1': ['a', 'b', 'c', 'd']}
 
a = pd.DataFrame(d)
b = pd.DataFrame()
d = {'id': [1, 2, 9, 8],
     'val1': ['p', 'q', 'r', 's']}
b = pd.DataFrame(d)
 
# left outer join
df = pd.merge(a, b, on='id', how='left')
df

id val1_x val1_y
0   1      a      p
1   2      b      q
2  10      c    NaN
3  12      d    NaN

In [16]:
#RIGHT JOIN


In [22]:
import pandas as pd

a = pd.DataFrame()
d = {'id': [1, 2, 10, 12],
     'val1': ['a', 'b', 'c', 'd']}
 
a = pd.DataFrame(d)
 
b = pd.DataFrame()
d = {'id': [1, 2, 9, 8],
     'val1': ['p', 'q', 'r', 's']}
b = pd.DataFrame(d)
 
# right outer join
df = pd.merge(a, b, on='id', how='right')
df

id val1_x val1_y
0   1      a      p
1   2      b      q
2   9    NaN      r
3   8    NaN      s

In [18]:
#FULL OUTER JOIN

In [24]:
import pandas as pd

a = pd.DataFrame()
d = {'id': [1, 2, 10, 12],
	'val1': ['a', 'b', 'c', 'd']}

a = pd.DataFrame(d)

# Creating dataframe b
b = pd.DataFrame()
d = {'id': [1, 2, 9, 8],
	'val1': ['p', 'q', 'r', 's']}
b = pd.DataFrame(d)

# full outer join
df = pd.merge(a, b, on='id', how='outer')
df


id val1_x val1_y
0   1      a      p
1   2      b      q
2   8    NaN      s
3   9    NaN      r
4  10      c    NaN
5  12      d    NaN

In [20]:
#INDEX JOIN

In [21]:
import pandas as pd

a = pd.DataFrame()

d = {'id': [1, 2, 10, 12],
	'val1': ['a', 'b', 'c', 'd']}

a = pd.DataFrame(d)

b = pd.DataFrame()
d = {'id': [1, 2, 9, 8],
	'val1': ['p', 'q', 'r', 's']}
b = pd.DataFrame(d)

# index join
df = pd.merge(a, b, left_index=True, right_index=True)
df


id_x val1_x  id_y val1_y
0     1      a     1      p
1     2      b     2      q
2    10      c     9      r
3    12      d     8      s